app:
  cdr-listener-topic: cdr-topic
  brt-producer-topic: brt-topic
  hrs-listener-topic: hrs-topic
  hrs-producer-month-topic: hrs-month-topic
  server:
spring:

  application:
    name: btr-service

  datasource:
#      url: jdbc:postgresql://nexign-postgresql2-1:5433/main
#      username: postgres
#      password: postgres
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081