app:
  generator:
    number-files: 3
    last-month: 12
    year: 2024
  scheduler:
    enable: true
    interval: 1m
  topic: cdr-topic
  server:
spring:
  application:
    name: cdr-service

  datasource:
#    url: jdbc:postgresql://nexign-postgresql1-1:5432/transactions
#    username: postgres
#    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
server:
  port: 8080