app:
#  scheduler:
#    enable: true
#    interval: 1m
  brtListenerTopic: brt-topic
  hrsProducerTopic: hrs-topic
  hrsProducerMonthNotifTopic: hrs-month-topic
  server: #localhost:9092
spring:
  application:
    name: hrs-service
  datasource:
#    url: jdbc:postgresql://localhost:5434/hrs
#    username: postgres
#    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
server:
  port: 8082