spring:
  datasource:
#    url: jdbc:postgresql://localhost:5433/main
#    username: postgres
#    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
server:
  port: 8083
spring-doc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
app:
  scheduler:
    interval: 1m

